In [ ]:
from tqdm import tqdm
from models import tokenizer, sentiment, emotion
from data import df

tqdm.pandas()

In [15]:
df["token_count"] = df["lyrics"].apply(
    lambda x: len(tokenizer.tokenize(x))
)

df.head()

,year,rank,artist,song,lyrics,sentiment,token_count
0,1950,1,Fats Domino,The Fat Man,"They call, they call me the fat man 'Cause I w...",0.591408,182
1,1950,2,Percy Mayfield,Please Send Me Someone To Love,"Understanding and peace of mind But, if it's n...",0.316507,281
2,1950,3,Ruth Brown,Teardrops From My Eyes,I think of you And that's the time I feel so b...,0.455756,201
3,1950,4,Nat King Cole,Mona Lisa,"Mona Lisa, Mona Lisa, men have named you You'r...",-0.310024,185
4,1950,5,Patti Page,Tennessee Waltz,When an old friend I happened to see I Introdu...,-0.554108,143

In [ ]:
df["sentiment"] = df["lyrics"].progress_apply(sentiment)

df.head()

100%|██████████| 679/679 [04:27<00:00,  2.54it/s]

,year,rank,artist,song,lyrics,sentiment
0,1950,1,Fats Domino,The Fat Man,"They call, they call me the fat man 'Cause I w...",0.591408
1,1950,2,Percy Mayfield,Please Send Me Someone To Love,"Understanding and peace of mind But, if it's n...",0.316507
2,1950,3,Ruth Brown,Teardrops From My Eyes,I think of you And that's the time I feel so b...,0.455756
3,1950,4,Nat King Cole,Mona Lisa,"Mona Lisa, Mona Lisa, men have named you You'r...",-0.310024
4,1950,5,Patti Page,Tennessee Waltz,When an old friend I happened to see I Introdu...,-0.554108

In [ ]:
df["emotion"] = df["lyrics"].progress_apply(
    lambda x: max(emotion(x), key=emotion(x).get)
)

df.head()

 77%|███████▋  | 526/679 [02:55<01:48,  1.40it/s]